v1.2.0
QuickDrone-Backend/pg-conn pull request #3
Opened 2024-02-03 19:29 UTC by zhikh23

Полный рефакторинг, добавлены тесты.
Исправлено множество ошибок, которые без тестов было бы найти очень сложно (например, незакрытые соединения в абсолютном большинстве функций).
Единообразный API взаимодействия, никакого деления на прод/тесты.

2024-02-04 12:28 UTC, TheStrikeM requested changes
Добавить контексты, и окей, будем использовать

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +	db, err = sqlx.Open("pgx", url)
Где зависимость от контекста? У меня коннекшн заканчивался, когда контекст кенселился, поэтому не стоит в название пула говорить, что коннекты утекают

Почему выбрал именно Open вместо ConnectContext?

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +func MigrateUp(dbUrl, migrationUrl string) error {
Зачем закрывать мигратор, если он включается на время тестов, а потом, как тест вырубается, он соответственно тоже отрубается?

Функцию создания коннекшена с миграциями ты на проде и на деве скорей всего использовать никогда не будешь, это все будет настраиваться через migrator

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn_test.go
> +	err = sqlx.Get(conn, &id, "SELECT id FROM test_table")
Вот тут тот факт, что ты не используешь Context одобряется, но в создании коннекта его очень важно использовать

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +func setupConnection(db *sqlx.DB, settings *ConnSettings) {
Нет передачи контекста - bad practices

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +func ConnectWithTries(url string, settings *ConnSettings, attempts int, attemptDuration time.Duration) (db *sqlx.DB, err error) {
Нет передачи контекста - bad practices

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +		db, err = Connect(url, settings)
нет контекста на выполнение коннекта, он может идти очень долго, а если он идёт очень долго - его надо скипать, поскольку наверняка что-то в таком случае не так

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +		db, err = Connect(url, settings)
Контекст в свою очередь передаётся из самого микросервиса, и таймаут там и указывается

2024-02-04 12:28 UTC, TheStrikeM commented on pgconn.go
> +func MigrateUp(dbUrl, migrationUrl string) error {
То, что обрубил зависимость Connect от MigrateUp - здорово, похвально

2024-02-04 12:28 UTC, TheStrikeM commented on docker-compose.test.yml
> +version: "3.8"
если ты хочешь писать нормальные тесты, которые не зависят от сторонник докерских библиотек, а реализуют это внутри - используй testcontainers

2024-02-04 12:40 UTC, merged

2024-02-05 11:49 UTC, zhikh23 commented on pgconn.go
> +func MigrateUp(dbUrl, migrationUrl string) error {
в том то и дело, что он сам не отрубается
коннект ещё будет висеть некоторое время после тестов
проверено тем, что у меня тесты падали из-за этого (жёсткое ограничение на один коннект)